language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'CREATE DATABASE SENDIT' -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to brian;" -U postgres
script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls

services:
  - postgresql


# safelist

