language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls

services:
  - postgresql


# safelist

