language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls
before_script:
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE USER foo WITH PASSWORD 'bar';" -U postgres
script:
  - nosetests --with-coverage --cover-package=app

after_success:
  - coveralls

services:
  - postgresql


# safelist

